## Euler Problem 133

A number consisting entirely of ones is called a repunit. We shall define R(k) to be a repunit of length k; for example, R(6) = 111111.

Let us consider repunits of the form R(10^n).

Although R(10), R(100), or R(1000) are not divisible by 17, R(10000) is divisible by 17. Yet there is no value of n for which R(10^n) will divide by 19. In fact, it is remarkable that 11, 17, 41, and 73 are the only four primes below one-hundred that can be a factor of R(10^n).

Find the sum of all the primes below one-hundred thousand that will never be a factor of R(10^n).

In [9]:
using Primes, Lazy, Combinatorics

`R(k) returns Repunit of size k`

In [10]:
R(k) = div(BigInt(10)^k - 1 ,9)

R (generic function with 1 method)

`order(R) returns the size of R(k), i.e., k`

In [11]:
order(R) = floor(Integer, log10(R)) + 1

order (generic function with 1 method)

Find first prime factors of R(n) = (10^k -1)/9 means:

(10^k -1)/9 = 0 mod(p) for p = primes

10^k = 1 mod(p) for p > 3, because 10^k =1 mod(3), i.e, all 3|10^k always has a remainder of 1

Use powermod(10,10^k,p) == 1 for all p > 3 to find factors


`R_ten_to(n,ds) takes 'n' from 10^n and returns 'ds' prime factors`

In [12]:
R_ten_to(n,ds) = 
@>> Lazy.primes drop(2) map(p->((powermod(10,10^n,p)==1,p))) filter(x->x[1]==true) map(last) take(ds)

R_ten_to (generic function with 1 method)

`R_ten_to_iter(n,upto) takes 'n' from 10^n and primes `upto` and returns sum of all prime factors found`

In [13]:
R_ten_to_iter(n,upto) = [p for p in primes(5,upto) if powermod(10,BigInt(10)^n,p) == 1]'

R_ten_to_iter (generic function with 1 method)

What are the prime divisors of various 10^n

In [19]:
@time R_ten_to(1,50)

  0.000008 seconds (21 allocations: 520 bytes)


(11 41 271 9091)

In [20]:
@time R_ten_to(2,50)

  0.000008 seconds (21 allocations: 520 bytes)


(11 41 101 251 271 3541 5051 9091 21401 25601 27961 60101)

In [15]:
@time R_ten_to(3,50)

  0.000007 seconds (21 allocations: 520 bytes)


(11 41 73 101 137 251 271 401 751 1201 1601 3541 4001 5051 9091 21001 21401 24001 25601 27961 60101 76001 162251 1378001 1610501 1676321)

In [21]:
@time R_ten_to(4,50)

  0.000008 seconds (21 allocations: 520 bytes)


(11 17 41 73 101 137 251 271 401 751 1201 1601 3541 4001 5051 9091 16001 21001 21401 24001 25601 27961 60101 76001 160001 162251 670001 952001 1378001 1610501 1676321 5070721)

In [16]:
@time R_ten_to(8,50)

  0.000008 seconds (21 allocations: 520 bytes)


(11 17 41 73 101 137 251 257 271 353 401 449 641 751 1201 1409 1601 3541 4001 4801 5051 9091 15361 16001 19841 21001 21401 24001 25601 27961 37501 43201 60101 62501 69857 76001 76801 160001 162251 453377 524801 544001 670001 952001 976193 980801 1378001 1610501 1634881 1676321)

Lazy prime implementation does not appear to allow for primes in excess of 67001. Use iterative implementation instead: `R_ten_to_iter(n,upto)`

### Euler Problem 133 Solution

By the Pigeon Hole Principal, there are only a limited number of primes, therefore, the an iterated approach and look for convergence. Iteration not shown. (This is not a solid proof).

In [25]:
@time ps = [p for p in R_ten_to_iter(20,10^5) if p < 10^5]

  0.173722 seconds (2.63 M allocations: 49.118 MiB)


40-element Array{Int64,1}:
    11
    17
    41
    73
   101
   137
   251
   257
   271
   353
   401
   449
   641
     ⋮
 24001
 25601
 27961
 37501
 40961
 43201
 60101
 62501
 65537
 69857
 76001
 76801

The list of primes not divisible into R(10^n) is the converse of the primes to be in ps < 100,000. Don't forget to add '2' and '3', which never divide R(10^n)

In [27]:
[p for p in primes(5,10^5) if !(p in ps)]

9550-element Array{Int64,1}:
     5
     7
    13
    19
    23
    29
    31
    37
    43
    47
    53
    59
    61
     ⋮
 99859
 99871
 99877
 99881
 99901
 99907
 99923
 99929
 99961
 99971
 99989
 99991

In [29]:
@time sum([p for p in primes(5,10^5) if !(p in ps)]) + 2 + 3

  0.061837 seconds (85.56 k allocations: 4.132 MiB)


453647705

### Scratch, Practice as well as a slow implementation solution

`Printing Utilities`

In [45]:
macro print_seq(aseq) 
    :(for p in $aseq println(p) end) 
end

@print_seq (macro with 1 method)

In [46]:
macro print_seq(aseq, lines)
    :(for p in take($aseq,$lines) println(p) end)
end

@print_seq (macro with 2 methods)

`stats(dict) returns attributes of dict`

In [47]:
function stats(dict)
    e = last(sort(collect(keys(dict))))
    #m = last(sort(collect(values(dict))))
    return("Dict[$e] = $(dict[e]), Size = $(length(dict))")
end

stats (generic function with 1 method)

`sorted_dict(dict) returns a sorted array of dictionary pairs`

In [6]:
sorted_dict(dict) = [(k,dict[k]) for k in sort(collect(keys(dict)))]

sorted_dict (generic function with 1 method)

`ds(n) = GCD(d, 10) = 1 | d<-1:inf`

In [7]:
ds = @>> Lazy.range(2) filter(x->gcd(x,10)==1);

In [8]:
take(10,ds)

(3 7 9 11 13 17 19 21 23 27)

`Rs_lazy returns a lazy sequence of R(n) | n <- 1:inf`

In [12]:
Rs_lazy = @>> Lazy.range(1) map(R);

`make_A_goal(Rs, goal) returns A[d], where goal is the maximum divisor and Rs is sequence of R(k), including a lazy sequence`

`factors(n) printable version of factor(n)`

In [13]:
factors(n) = join([v==1 ? "$k" : "$k^$v" for (k,v) in pairs(factor(n))], " ⋅ ")

factors (generic function with 1 method)

In [14]:
factors(72)

"2^3 ⋅ 3^2"

`returns all the factors listed out`

In [15]:
all_factors(n) = reduce(vcat,[fill(p,i) for (p,i) in pairs(factor(n))])'

all_factors (generic function with 1 method)

In [16]:
all_factors(72)

1×5 LinearAlgebra.Adjoint{Int64,Array{Int64,1}}:
 2  2  2  3  3

`powermod(x::Integer, p::Integer, m)` Returns x^p (mod m)

`A(d) = k, where k is the lowest order R(m) and gcd(d,10) = 1`

In [4]:
function A(d)
    k = 1
    d = d * 9
    while powermod(10, k, d) != 1 # Returns 10^k (mod d)
        k = k + 1
    end
    return(k)
end

A (generic function with 1 method)

In [23]:
@time A_d =sort([(d,A(d)) for d in take(10000,ds)]);

 13.414118 seconds (195.68 k allocations: 6.140 MiB)


In [25]:
stats(A_d)

"Dict[10000] = (24999, 96), Size = 10000"

In [26]:
@print_seq A_d

(1, 1)
(3, 3)
(7, 6)
(9, 9)
(11, 2)
(13, 6)
(17, 16)
(19, 18)
(21, 6)
(23, 22)
(27, 27)
(29, 28)
(31, 15)
(33, 6)
(37, 3)
(39, 6)
(41, 5)
(43, 21)
(47, 46)
(49, 42)
(51, 48)
(53, 13)
(57, 18)
(59, 58)
(61, 60)
(63, 18)
(67, 33)
(69, 66)
(71, 35)
(73, 8)
(77, 6)
(79, 13)
(81, 81)
(83, 41)
(87, 84)
(89, 44)
(91, 6)
(93, 15)
(97, 96)
(99, 18)
(101, 4)
(103, 34)
(107, 53)
(109, 108)
(111, 3)
(113, 112)
(117, 18)
(119, 48)
(121, 22)
(123, 15)
(127, 42)
(129, 21)
(131, 130)
(133, 18)
(137, 8)
(139, 46)
(141, 138)
(143, 6)
(147, 42)
(149, 148)
(151, 75)
(153, 144)
(157, 78)
(159, 39)
(161, 66)
(163, 81)
(167, 166)
(169, 78)
(171, 18)
(173, 43)
(177, 174)
(179, 178)
(181, 180)
(183, 60)
(187, 16)
(189, 54)
(191, 95)
(193, 192)
(197, 98)
(199, 99)
(201, 33)
(203, 84)
(207, 198)
(209, 18)
(211, 30)
(213, 105)
(217, 30)
(219, 24)
(221, 48)
(223, 222)
(227, 113)
(229, 228)
(231, 6)
(233, 232)
(237, 39)
(239, 7)
(241, 30)
(243, 243)
(247, 18)
(249, 123)
(251, 50)
(253, 22)
(257, 256)
(259, 6)
(261,

(2133, 351)
(2137, 2136)
(2139, 330)
(2141, 2140)
(2143, 2142)
(2147, 1008)
(2149, 306)
(2151, 63)
(2153, 2152)
(2157, 1077)
(2159, 336)
(2161, 30)
(2163, 102)
(2167, 98)
(2169, 90)
(2171, 498)
(2173, 65)
(2177, 930)
(2179, 2178)
(2181, 726)
(2183, 174)
(2187, 2187)
(2189, 198)
(2191, 312)
(2193, 336)
(2197, 1014)
(2199, 183)
(2201, 105)
(2203, 1101)
(2207, 2206)
(2209, 2162)
(2211, 66)
(2213, 553)
(2217, 246)
(2219, 474)
(2221, 2220)
(2223, 18)
(2227, 1040)
(2229, 2226)
(2231, 1056)
(2233, 84)
(2237, 1118)
(2239, 1119)
(2241, 1107)
(2243, 1121)
(2247, 318)
(2249, 258)
(2251, 2250)
(2253, 375)
(2257, 60)
(2259, 450)
(2261, 144)
(2263, 120)
(2267, 1133)
(2269, 2268)
(2271, 27)
(2273, 2272)
(2277, 198)
(2279, 273)
(2281, 228)
(2283, 1140)
(2287, 762)
(2289, 108)
(2291, 364)
(2293, 1146)
(2297, 2296)
(2299, 198)
(2301, 174)
(2303, 966)
(2307, 192)
(2309, 2308)
(2311, 231)
(2313, 2304)
(2317, 330)
(2319, 579)
(2321, 30)
(2323, 44)
(2327, 534)
(2329, 16)
(2331, 18)
(2333, 583)
(2337, 90)
(2

(4219, 4218)
(4221, 198)
(4223, 170)
(4227, 96)
(4229, 4228)
(4231, 2115)
(4233, 1968)
(4237, 666)
(4239, 702)
(4241, 1060)
(4243, 2121)
(4247, 120)
(4249, 606)
(4251, 108)
(4253, 1063)
(4257, 126)
(4259, 4258)
(4261, 4260)
(4263, 84)
(4267, 400)
(4269, 474)
(4271, 2135)
(4273, 1424)
(4277, 138)
(4279, 388)
(4281, 2139)
(4283, 2141)
(4287, 1428)
(4289, 2144)
(4291, 102)
(4293, 1053)
(4297, 1432)
(4299, 4296)
(4301, 176)
(4303, 330)
(4307, 232)
(4309, 690)
(4311, 2151)
(4313, 2034)
(4317, 2157)
(4319, 264)
(4321, 1036)
(4323, 390)
(4327, 4326)
(4329, 18)
(4331, 420)
(4333, 618)
(4337, 4336)
(4339, 4338)
(4341, 1446)
(4343, 84)
(4347, 594)
(4349, 4348)
(4351, 684)
(4353, 870)
(4357, 242)
(4359, 726)
(4361, 924)
(4363, 2181)
(4367, 198)
(4369, 256)
(4371, 690)
(4373, 1093)
(4377, 162)
(4379, 2100)
(4381, 336)
(4383, 486)
(4387, 265)
(4389, 18)
(4391, 2195)
(4393, 2090)
(4397, 314)
(4399, 533)
(4401, 81)
(4403, 48)
(4407, 336)
(4409, 551)
(4411, 200)
(4413, 735)
(4417, 630)
(4419, 4410)
(4

(6521, 815)
(6523, 592)
(6527, 3180)
(6529, 1088)
(6531, 930)
(6533, 46)
(6537, 2178)
(6539, 1506)
(6541, 30)
(6543, 2178)
(6547, 1091)
(6549, 174)
(6551, 3275)
(6553, 6552)
(6557, 533)
(6559, 936)
(6561, 6561)
(6563, 3281)
(6567, 198)
(6569, 1642)
(6571, 6570)
(6573, 312)
(6577, 2192)
(6579, 1008)
(6581, 1316)
(6583, 3164)
(6587, 2820)
(6589, 598)
(6591, 1014)
(6593, 3114)
(6597, 549)
(6599, 3299)
(6601, 330)
(6603, 105)
(6607, 2202)
(6609, 1101)
(6611, 300)
(6613, 1552)
(6617, 1524)
(6619, 6618)
(6621, 6618)
(6623, 534)
(6627, 6486)
(6629, 2838)
(6631, 1044)
(6633, 198)
(6637, 474)
(6639, 1659)
(6641, 1596)
(6643, 24)
(6647, 2992)
(6649, 540)
(6651, 738)
(6653, 3326)
(6657, 474)
(6659, 6658)
(6661, 6660)
(6663, 2220)
(6667, 3248)
(6669, 54)
(6671, 2856)
(6673, 6672)
(6677, 202)
(6679, 3339)
(6681, 3120)
(6683, 405)
(6687, 6678)
(6689, 1672)
(6691, 6690)
(6693, 1056)
(6697, 180)
(6699, 84)
(6701, 6700)
(6703, 6702)
(6707, 288)
(6709, 6708)
(6711, 3354)
(6713, 168)
(6717, 1119)
(6719, 

(8827, 96)
(8829, 324)
(8831, 4415)
(8833, 88)
(8837, 4418)
(8839, 4419)
(8841, 420)
(8843, 21)
(8847, 8838)
(8849, 553)
(8851, 2158)
(8853, 678)
(8857, 208)
(8859, 984)
(8861, 8860)
(8863, 8862)
(8867, 4433)
(8869, 1260)
(8871, 4434)
(8873, 4194)
(8877, 804)
(8879, 2046)
(8881, 2173)
(8883, 1242)
(8887, 8886)
(8889, 4443)
(8891, 4176)
(8893, 2223)
(8897, 30)
(8899, 202)
(8901, 1386)
(8903, 4284)
(8907, 1113)
(8909, 4350)
(8911, 198)
(8913, 2970)
(8917, 30)
(8919, 495)
(8921, 810)
(8923, 1487)
(8927, 1456)
(8929, 144)
(8931, 228)
(8933, 2233)
(8937, 2970)
(8939, 1914)
(8941, 2980)
(8943, 30)
(8947, 4268)
(8949, 234)
(8951, 4475)
(8953, 1278)
(8957, 78)
(8959, 4080)
(8961, 1428)
(8963, 4481)
(8967, 420)
(8969, 4484)
(8971, 8970)
(8973, 1494)
(8977, 4370)
(8979, 120)
(8981, 3846)
(8983, 690)
(8987, 126)
(8989, 44)
(8991, 243)
(8993, 4048)
(8997, 4497)
(8999, 4499)
(9001, 1125)
(9003, 1500)
(9007, 3002)
(9009, 18)
(9011, 9010)
(9013, 2253)
(9017, 210)
(9019, 4340)
(9021, 480)
(9023, 276)


(11047, 11046)
(11049, 84)
(11051, 5376)
(11053, 1578)
(11057, 11056)
(11059, 11058)
(11061, 11052)
(11063, 66)
(11067, 240)
(11069, 11068)
(11071, 615)
(11073, 1230)
(11077, 234)
(11079, 369)
(11081, 4746)
(11083, 1847)
(11087, 482)
(11089, 426)
(11091, 3696)
(11093, 2773)
(11097, 648)
(11099, 252)
(11101, 2608)
(11103, 11100)
(11107, 5348)
(11109, 1518)
(11111, 5)
(11113, 3704)
(11117, 2779)
(11119, 5559)
(11121, 336)
(11123, 4746)
(11127, 3708)
(11129, 2685)
(11131, 11130)
(11133, 1854)
(11137, 42)
(11139, 1794)
(11141, 2568)
(11143, 506)
(11147, 2730)
(11149, 11148)
(11151, 1566)
(11153, 5274)
(11157, 5577)
(11159, 5579)
(11161, 310)
(11163, 3660)
(11167, 78)
(11169, 144)
(11171, 11170)
(11173, 5586)
(11177, 11176)
(11179, 798)
(11181, 3726)
(11183, 390)
(11187, 1008)
(11189, 5478)
(11191, 1710)
(11193, 30)
(11197, 2799)
(11199, 933)
(11201, 5346)
(11203, 5264)
(11207, 600)
(11209, 1018)
(11211, 12)
(11213, 2803)
(11217, 3738)
(11219, 2586)
(11221, 1596)
(11223, 252)
(11227, 1836)


(13289, 96)
(13291, 13290)
(13293, 90)
(13297, 13296)
(13299, 30)
(13301, 6486)
(13303, 650)
(13307, 1140)
(13309, 4436)
(13311, 3024)
(13313, 13312)
(13317, 2112)
(13319, 6300)
(13321, 258)
(13323, 2220)
(13327, 4442)
(13329, 6660)
(13331, 13330)
(13333, 99)
(13337, 13336)
(13339, 13338)
(13341, 4446)
(13343, 202)
(13347, 2223)
(13349, 5718)
(13351, 78)
(13353, 13350)
(13357, 342)
(13359, 120)
(13361, 645)
(13363, 2706)
(13367, 13366)
(13369, 3220)
(13371, 13368)
(13373, 3255)
(13377, 294)
(13379, 6288)
(13381, 13380)
(13383, 13374)
(13387, 1216)
(13389, 13386)
(13391, 5736)
(13393, 6554)
(13397, 6698)
(13399, 957)
(13401, 2232)
(13403, 618)
(13407, 540)
(13409, 286)
(13411, 13410)
(13413, 6288)
(13417, 4472)
(13419, 1890)
(13421, 13420)
(13423, 2160)
(13427, 308)
(13429, 1032)
(13431, 66)
(13433, 36)
(13437, 3357)
(13439, 3300)
(13441, 6720)
(13443, 6720)
(13447, 336)
(13449, 249)
(13451, 13450)
(13453, 1222)
(13457, 13456)
(13459, 2184)
(13461, 96)
(13463, 13462)
(13467, 2211)
(1346

(15607, 15606)
(15609, 462)
(15611, 7656)
(15613, 600)
(15617, 1056)
(15619, 15618)
(15621, 210)
(15623, 7344)
(15627, 372)
(15629, 15628)
(15631, 84)
(15633, 5184)
(15637, 2466)
(15639, 600)
(15641, 391)
(15643, 7821)
(15647, 15646)
(15649, 489)
(15651, 414)
(15653, 158)
(15657, 2448)
(15659, 3354)
(15661, 5220)
(15663, 7458)
(15667, 7833)
(15669, 5220)
(15671, 1567)
(15673, 2238)
(15677, 3840)
(15679, 2613)
(15681, 2613)
(15683, 7841)
(15687, 2214)
(15689, 3780)
(15691, 1680)
(15693, 7845)
(15697, 1426)
(15699, 5232)
(15701, 6726)
(15703, 1910)
(15707, 2576)
(15709, 682)
(15711, 231)
(15713, 7434)
(15717, 390)
(15719, 1428)
(15721, 1287)
(15723, 873)
(15727, 15726)
(15729, 2226)
(15731, 15730)
(15733, 2622)
(15737, 15736)
(15739, 15738)
(15741, 702)
(15743, 258)
(15747, 1260)
(15749, 15748)
(15751, 828)
(15753, 3828)
(15757, 2250)
(15759, 2448)
(15761, 394)
(15763, 1432)
(15767, 15766)
(15769, 606)
(15771, 750)
(15773, 7886)
(15777, 5256)
(15779, 7620)
(15781, 2562)
(15783, 3156)
(15

(17923, 8961)
(17927, 294)
(17929, 8964)
(17931, 966)
(17933, 1469)
(17937, 5976)
(17939, 17938)
(17941, 696)
(17943, 17940)
(17947, 520)
(17949, 960)
(17951, 8652)
(17953, 1380)
(17957, 8978)
(17959, 8979)
(17961, 8979)
(17963, 770)
(17967, 4368)
(17969, 1200)
(17971, 17970)
(17973, 8982)
(17977, 856)
(17979, 1380)
(17981, 17980)
(17983, 2562)
(17987, 8993)
(17989, 5996)
(17991, 999)
(17993, 8514)
(17997, 2568)
(17999, 1095)
(18001, 8786)
(18003, 96)
(18007, 818)
(18009, 8316)
(18011, 1230)
(18013, 9006)
(18017, 8778)
(18019, 486)
(18021, 858)
(18023, 8844)
(18027, 9009)
(18029, 1628)
(18031, 72)
(18033, 18030)
(18037, 848)
(18039, 78)
(18041, 220)
(18043, 291)
(18047, 2578)
(18049, 1128)
(18051, 546)
(18053, 7734)
(18057, 462)
(18059, 18058)
(18061, 18060)
(18063, 5994)
(18067, 924)
(18069, 1422)
(18071, 8496)
(18073, 390)
(18077, 4519)
(18079, 356)
(18081, 630)
(18083, 4134)
(18087, 18084)
(18089, 9044)
(18091, 2964)
(18093, 81)
(18097, 6032)
(18099, 6030)
(18101, 8646)
(18103, 420)

(20243, 4890)
(20247, 1584)
(20249, 2531)
(20251, 786)
(20253, 546)
(20257, 9890)
(20259, 2250)
(20261, 20260)
(20263, 440)
(20267, 4674)
(20269, 2252)
(20271, 4872)
(20273, 288)
(20277, 3375)
(20279, 8688)
(20281, 2384)
(20283, 5070)
(20287, 966)
(20289, 483)
(20291, 1666)
(20293, 222)
(20297, 20296)
(20299, 4966)
(20301, 132)
(20303, 3328)
(20307, 966)
(20309, 9702)
(20311, 3204)
(20313, 180)
(20317, 1846)
(20319, 156)
(20321, 8706)
(20323, 3387)
(20327, 20326)
(20329, 700)
(20331, 4050)
(20333, 10166)
(20337, 20334)
(20339, 1806)
(20341, 4068)
(20343, 1356)
(20347, 10173)
(20349, 144)
(20351, 9936)
(20353, 6784)
(20357, 5089)
(20359, 10179)
(20361, 264)
(20363, 8724)
(20367, 360)
(20369, 1273)
(20371, 1566)
(20373, 2037)
(20377, 210)
(20379, 6792)
(20381, 2508)
(20383, 432)
(20387, 252)
(20389, 6796)
(20391, 2910)
(20393, 20392)
(20397, 522)
(20399, 10199)
(20401, 9746)
(20403, 10197)
(20407, 20406)
(20409, 10203)
(20411, 20410)
(20413, 296)
(20417, 400)
(20419, 1458)
(20421, 2268)


(22543, 7514)
(22547, 9660)
(22549, 22548)
(22551, 11274)
(22553, 10674)
(22557, 408)
(22559, 10608)
(22561, 438)
(22563, 1188)
(22567, 22566)
(22569, 11283)
(22571, 4514)
(22573, 5643)
(22577, 1590)
(22579, 3696)
(22581, 576)
(22583, 342)
(22587, 5646)
(22589, 9660)
(22591, 1260)
(22593, 10608)
(22597, 11078)
(22599, 3645)
(22601, 2784)
(22603, 3228)
(22607, 138)
(22609, 10802)
(22611, 7536)
(22613, 5653)
(22617, 3222)
(22619, 22618)
(22621, 7540)
(22623, 22620)
(22627, 1936)
(22629, 198)
(22631, 780)
(22633, 1740)
(22637, 11318)
(22639, 11319)
(22641, 11319)
(22643, 11321)
(22647, 7548)
(22649, 140)
(22651, 1510)
(22653, 11313)
(22657, 3726)
(22659, 246)
(22661, 1680)
(22663, 5590)
(22667, 10728)
(22669, 22668)
(22671, 684)
(22673, 390)
(22677, 11337)
(22679, 11339)
(22681, 51)
(22683, 1890)
(22687, 462)
(22689, 630)
(22691, 22690)
(22693, 2062)
(22697, 22696)
(22699, 2522)
(22701, 1518)
(22703, 1240)
(22707, 21924)
(22709, 22708)
(22711, 582)
(22713, 3696)
(22717, 5679)
(22719, 1893

(24851, 4970)
(24853, 5992)
(24857, 858)
(24859, 24858)
(24861, 8286)
(24863, 506)
(24867, 1377)
(24869, 5736)
(24871, 144)
(24873, 24870)
(24877, 12438)
(24879, 2073)
(24881, 4094)
(24883, 12284)
(24887, 1010)
(24889, 3111)
(24891, 24888)
(24893, 120)
(24897, 1344)
(24899, 762)
(24901, 672)
(24903, 8298)
(24907, 12453)
(24909, 3762)
(24911, 364)
(24913, 3558)
(24917, 12458)
(24919, 12459)
(24921, 1890)
(24923, 12461)
(24927, 3558)
(24929, 768)
(24931, 12296)
(24933, 4155)
(24937, 2266)
(24939, 1296)
(24941, 10668)
(24943, 8314)
(24947, 36)
(24949, 1020)
(24951, 462)
(24953, 24952)
(24957, 12006)
(24959, 2268)
(24961, 2052)
(24963, 78)
(24967, 24966)
(24969, 420)
(24971, 24970)
(24973, 336)
(24977, 24976)
(24979, 8326)
(24981, 54)
(24983, 1722)
(24987, 1041)
(24989, 24988)
(24991, 2046)
(24993, 24984)
(24997, 3570)
(24999, 96)


In [27]:
D_k = sort(map(p->(p[2],p[1]), A_d));
@print_seq D_k

(1, 1)
(2, 11)
(3, 3)
(3, 37)
(3, 111)
(4, 101)
(4, 1111)
(5, 41)
(5, 271)
(5, 11111)
(6, 7)
(6, 13)
(6, 21)
(6, 33)
(6, 39)
(6, 77)
(6, 91)
(6, 143)
(6, 231)
(6, 259)
(6, 273)
(6, 407)
(6, 429)
(6, 481)
(6, 777)
(6, 1001)
(6, 1221)
(6, 1443)
(6, 2849)
(6, 3003)
(6, 3367)
(6, 5291)
(6, 8547)
(6, 10101)
(6, 15873)
(7, 239)
(7, 4649)
(8, 73)
(8, 137)
(8, 803)
(8, 1507)
(8, 7373)
(8, 10001)
(8, 13837)
(9, 9)
(9, 333)
(10, 451)
(10, 2981)
(10, 9091)
(11, 21649)
(12, 303)
(12, 707)
(12, 1313)
(12, 2121)
(12, 3333)
(12, 3737)
(12, 3939)
(12, 7777)
(12, 9191)
(12, 9901)
(12, 11211)
(12, 14443)
(12, 23331)
(13, 53)
(13, 79)
(13, 4187)
(14, 2629)
(15, 31)
(15, 93)
(15, 123)
(15, 813)
(15, 1147)
(15, 1271)
(15, 1517)
(15, 3441)
(15, 3813)
(15, 4551)
(15, 8401)
(15, 10027)
(16, 17)
(16, 187)
(16, 1241)
(16, 1717)
(16, 2329)
(16, 13651)
(16, 18887)
(18, 19)
(18, 57)
(18, 63)
(18, 99)
(18, 117)
(18, 133)
(18, 171)
(18, 209)
(18, 247)
(18, 399)
(18, 627)
(18, 693)
(18, 703)
(18, 741)
(18, 819)
(18, 

(110, 943)
(110, 3641)
(110, 4961)
(110, 5171)
(110, 6233)
(110, 7613)
(110, 10373)
(110, 13571)
(110, 14531)
(111, 1369)
(111, 4107)
(112, 113)
(112, 493)
(112, 1243)
(112, 1921)
(112, 3277)
(112, 4063)
(112, 4777)
(112, 5423)
(112, 8249)
(112, 11413)
(112, 15481)
(112, 21131)
(113, 227)
(116, 349)
(116, 3839)
(116, 5959)
(116, 20591)
(117, 477)
(117, 711)
(117, 17649)
(118, 1889)
(118, 20779)
(120, 2263)
(120, 4247)
(120, 4453)
(120, 6789)
(120, 8357)
(120, 8979)
(120, 12741)
(120, 13359)
(120, 15403)
(120, 15841)
(120, 16851)
(120, 17593)
(120, 20951)
(120, 24893)
(121, 15973)
(122, 8063)
(123, 249)
(123, 3071)
(123, 3693)
(123, 9213)
(125, 751)
(126, 441)
(126, 817)
(126, 931)
(126, 1143)
(126, 2413)
(126, 2451)
(126, 2709)
(126, 2793)
(126, 4257)
(126, 4541)
(126, 4851)
(126, 5031)
(126, 5719)
(126, 5733)
(126, 7239)
(126, 7353)
(126, 8001)
(126, 8379)
(126, 8987)
(126, 10241)
(126, 10621)
(126, 12103)
(126, 12573)
(126, 13623)
(126, 14859)
(126, 15057)
(126, 16317)
(126, 16891)
(

(258, 2249)
(258, 3633)
(258, 5709)
(258, 6747)
(258, 13321)
(258, 15743)
(258, 24739)
(259, 2591)
(260, 13231)
(260, 21361)
(261, 523)
(261, 1569)
(261, 4707)
(261, 19351)
(262, 263)
(262, 2893)
(264, 1851)
(264, 2377)
(264, 4319)
(264, 4891)
(264, 5037)
(264, 7131)
(264, 8021)
(264, 9179)
(264, 9453)
(264, 11753)
(264, 12957)
(264, 14673)
(264, 16369)
(264, 16639)
(264, 19491)
(264, 20361)
(264, 21827)
(264, 22057)
(264, 22829)
(264, 24063)
(265, 4387)
(266, 17567)
(267, 9613)
(268, 269)
(268, 2959)
(268, 4021)
(270, 5697)
(270, 5859)
(270, 6481)
(270, 6507)
(270, 7749)
(270, 9207)
(270, 10881)
(270, 12177)
(270, 14391)
(270, 15903)
(270, 19443)
(270, 21033)
(271, 1627)
(272, 289)
(272, 1751)
(272, 3179)
(272, 19261)
(272, 21097)
(273, 1093)
(273, 1641)
(273, 2279)
(273, 3279)
(273, 3397)
(273, 6837)
(273, 10191)
(273, 20239)
(273, 23521)
(275, 7151)
(275, 15401)
(276, 829)
(276, 2487)
(276, 3867)
(276, 5803)
(276, 9023)
(276, 9119)
(276, 10777)
(276, 14241)
(276, 16757)
(276, 17409)

(486, 3409)
(486, 4383)
(486, 4617)
(486, 5357)
(486, 6331)
(486, 9253)
(486, 10227)
(486, 13149)
(486, 16071)
(486, 18019)
(486, 18711)
(486, 18993)
(486, 22113)
(487, 11689)
(489, 15649)
(490, 491)
(490, 5401)
(490, 8077)
(490, 13987)
(490, 18131)
(490, 20131)
(491, 3929)
(494, 16313)
(495, 991)
(495, 2973)
(495, 6169)
(495, 8159)
(495, 8919)
(495, 11889)
(495, 12307)
(495, 16277)
(495, 18507)
(495, 18693)
(495, 24477)
(495, 24723)
(498, 499)
(498, 501)
(498, 1169)
(498, 1497)
(498, 2171)
(498, 2991)
(498, 3493)
(498, 3507)
(498, 5489)
(498, 5511)
(498, 6179)
(498, 6487)
(498, 6513)
(498, 6979)
(498, 10479)
(498, 12859)
(498, 12961)
(498, 15197)
(498, 16467)
(498, 18463)
(498, 18537)
(498, 19461)
(498, 20937)
(498, 23881)
(499, 20959)
(500, 4001)
(502, 503)
(502, 5533)
(503, 7043)
(504, 19053)
(506, 529)
(506, 1081)
(506, 3197)
(506, 5687)
(506, 5819)
(506, 11143)
(506, 11891)
(506, 16819)
(506, 23299)
(506, 24863)
(508, 509)
(508, 3049)
(508, 5599)
(508, 7621)
(510, 3193)
(510, 9579

(826, 9097)
(828, 4969)
(828, 7461)
(828, 11601)
(828, 14907)
(828, 15751)
(828, 24491)
(830, 6847)
(832, 3329)
(833, 1667)
(834, 1671)
(834, 3899)
(834, 7241)
(834, 7509)
(834, 11697)
(834, 17521)
(834, 18381)
(834, 20609)
(834, 21723)
(838, 9229)
(840, 15549)
(843, 1689)
(843, 3373)
(843, 10119)
(843, 20831)
(846, 5377)
(846, 11851)
(846, 16131)
(846, 17829)
(846, 18623)
(846, 22009)
(848, 1819)
(848, 18037)
(848, 20009)
(852, 1707)
(852, 3983)
(852, 7397)
(852, 11949)
(852, 16189)
(852, 18777)
(852, 21053)
(852, 22191)
(852, 23007)
(853, 5119)
(853, 13649)
(855, 1719)
(855, 6841)
(855, 20523)
(856, 857)
(856, 9427)
(856, 17977)
(858, 3611)
(858, 3657)
(858, 3887)
(858, 5451)
(858, 6007)
(858, 8533)
(858, 10519)
(858, 10833)
(858, 11323)
(858, 11661)
(858, 12719)
(858, 15847)
(858, 18021)
(858, 18997)
(858, 19239)
(858, 20449)
(858, 23621)
(858, 24857)
(860, 7741)
(861, 3569)
(861, 5169)
(861, 10707)
(862, 863)
(862, 9493)
(864, 2619)
(864, 9531)
(864, 10573)
(864, 12123)
(864, 17307

(1296, 24939)
(1298, 6491)
(1299, 15591)
(1300, 1301)
(1300, 14311)
(1302, 1303)
(1302, 3909)
(1302, 9121)
(1302, 14333)
(1302, 16039)
(1302, 16939)
(1302, 18277)
(1304, 2609)
(1305, 16213)
(1305, 21443)
(1306, 14377)
(1310, 3931)
(1310, 10783)
(1314, 2637)
(1314, 5567)
(1314, 7893)
(1314, 8341)
(1314, 16663)
(1314, 16701)
(1314, 18459)
(1315, 13151)
(1316, 6581)
(1316, 19111)
(1318, 14509)
(1320, 2643)
(1320, 6167)
(1320, 11453)
(1320, 18481)
(1320, 18501)
(1320, 19127)
(1323, 21169)
(1323, 23841)
(1326, 1327)
(1326, 3101)
(1326, 3981)
(1326, 5759)
(1326, 9289)
(1326, 9303)
(1326, 14597)
(1326, 14619)
(1326, 16171)
(1326, 16377)
(1326, 17251)
(1326, 17277)
(1326, 17407)
(1326, 24411)
(1328, 2839)
(1328, 16949)
(1329, 18609)
(1332, 1341)
(1332, 2831)
(1332, 8493)
(1332, 9387)
(1332, 14751)
(1332, 17433)
(1332, 19817)
(1333, 5333)
(1334, 2773)
(1334, 8201)
(1335, 2671)
(1335, 8013)
(1338, 18739)
(1340, 11029)
(1341, 24147)
(1342, 16859)
(1344, 5597)
(1344, 8299)
(1344, 9457)
(1344, 1679

(1944, 11667)
(1944, 17739)
(1948, 1949)
(1948, 21439)
(1950, 5851)
(1950, 17553)
(1950, 19781)
(1950, 23707)
(1953, 3907)
(1953, 11721)
(1955, 3911)
(1958, 3917)
(1958, 4117)
(1958, 17623)
(1958, 21659)
(1959, 3921)
(1959, 11757)
(1961, 3923)
(1965, 24397)
(1968, 4233)
(1968, 9877)
(1968, 12563)
(1968, 18343)
(1971, 11853)
(1973, 3947)
(1974, 1977)
(1974, 4613)
(1974, 8567)
(1974, 13839)
(1974, 13867)
(1974, 21747)
(1974, 24383)
(1976, 24221)
(1977, 3957)
(1978, 1979)
(1978, 8131)
(1978, 21769)
(1978, 24047)
(1980, 4163)
(1980, 5949)
(1980, 12127)
(1980, 12139)
(1980, 12489)
(1980, 12559)
(1980, 12627)
(1980, 16109)
(1980, 21901)
(1980, 24217)
(1980, 24831)
(1984, 5953)
(1986, 13909)
(1988, 9941)
(1988, 16501)
(1989, 3987)
(1989, 16271)
(1989, 24253)
(1992, 5979)
(1992, 13951)
(1995, 8213)
(1995, 24639)
(1998, 6021)
(1998, 13993)
(1998, 21989)
(2000, 12767)
(2000, 16001)
(2002, 8009)
(2002, 12581)
(2002, 22033)
(2002, 24539)
(2007, 12043)
(2007, 24093)
(2010, 6033)
(2010, 14077)
(2011

(2948, 23941)
(2950, 11801)
(2958, 5919)
(2958, 13811)
(2958, 18231)
(2960, 24313)
(2961, 5923)
(2961, 17769)
(2964, 12137)
(2964, 18091)
(2970, 2971)
(2970, 8913)
(2970, 8937)
(2970, 19251)
(2970, 20797)
(2975, 23801)
(2979, 17883)
(2980, 8941)
(2985, 17911)
(2985, 24707)
(2986, 20903)
(2990, 6157)
(2990, 18209)
(2992, 6647)
(2993, 5987)
(2994, 5991)
(2994, 13979)
(2996, 18647)
(3002, 9007)
(3003, 6009)
(3009, 12037)
(3010, 3011)
(3016, 12349)
(3016, 18407)
(3018, 3019)
(3018, 6037)
(3018, 9057)
(3018, 15091)
(3018, 18111)
(3018, 21133)
(3021, 6043)
(3021, 18129)
(3021, 24169)
(3022, 3023)
(3024, 3051)
(3024, 6443)
(3024, 9099)
(3024, 12317)
(3024, 12557)
(3024, 13311)
(3024, 18619)
(3024, 19329)
(3024, 19737)
(3024, 21217)
(3024, 21357)
(3024, 22491)
(3026, 6053)
(3026, 15131)
(3026, 18437)
(3029, 24751)
(3030, 18817)
(3033, 6067)
(3033, 18201)
(3036, 12549)
(3036, 19067)
(3036, 24653)
(3039, 6081)
(3039, 18237)
(3042, 6093)
(3042, 9127)
(3042, 12863)
(3042, 19773)
(3049, 12197)
(305

(4433, 8867)
(4434, 8871)
(4434, 20699)
(4436, 13309)
(4442, 13327)
(4443, 8889)
(4446, 4447)
(4446, 13341)
(4446, 19133)
(4450, 4451)
(4452, 9309)
(4452, 21721)
(4456, 4457)
(4458, 4461)
(4458, 10409)
(4458, 19331)
(4462, 4463)
(4464, 18989)
(4472, 13417)
(4475, 8951)
(4481, 8963)
(4482, 4509)
(4482, 13473)
(4484, 8969)
(4485, 18569)
(4496, 9571)
(4497, 8997)
(4499, 8999)
(4504, 13513)
(4512, 13539)
(4514, 22571)
(4515, 18533)
(4518, 4527)
(4518, 9557)
(4519, 18077)
(4521, 9043)
(4522, 13567)
(4524, 9049)
(4530, 10577)
(4530, 19643)
(4533, 9067)
(4544, 13633)
(4548, 13647)
(4554, 4761)
(4554, 9353)
(4554, 9729)
(4554, 10051)
(4554, 18659)
(4554, 19247)
(4554, 20539)
(4560, 9707)
(4560, 9741)
(4560, 22729)
(4562, 13687)
(4564, 18937)
(4566, 4567)
(4566, 10661)
(4566, 13701)
(4566, 19799)
(4572, 4581)
(4572, 9671)
(4578, 9157)
(4582, 4583)
(4582, 18329)
(4582, 18703)
(4586, 9173)
(4592, 9379)
(4593, 9187)
(4599, 9199)
(4600, 18401)
(4600, 18847)
(4601, 9203)
(4603, 18413)
(4613, 9227)
(

(7130, 14617)
(7134, 14691)
(7144, 21433)
(7146, 21447)
(7164, 21501)
(7166, 21499)
(7173, 14347)
(7176, 7177)
(7176, 14711)
(7176, 21531)
(7179, 14361)
(7192, 7193)
(7193, 14387)
(7194, 16793)
(7196, 21589)
(7197, 14397)
(7206, 7207)
(7206, 21621)
(7218, 7219)
(7218, 14437)
(7218, 21657)
(7220, 21661)
(7228, 7229)
(7230, 7233)
(7230, 16877)
(7236, 7263)
(7238, 15157)
(7239, 14479)
(7244, 14489)
(7246, 7247)
(7246, 21739)
(7248, 7251)
(7248, 16919)
(7259, 14519)
(7266, 7269)
(7266, 16961)
(7266, 17003)
(7280, 14561)
(7280, 14803)
(7280, 15487)
(7295, 14591)
(7296, 21891)
(7298, 14857)
(7305, 14613)
(7308, 7309)
(7308, 7569)
(7308, 15167)
(7308, 15399)
(7308, 15979)
(7308, 21927)
(7313, 14627)
(7314, 15087)
(7314, 21943)
(7319, 14639)
(7332, 14667)
(7338, 7341)
(7338, 17129)
(7344, 7803)
(7344, 15623)
(7348, 7349)
(7358, 14717)
(7361, 14723)
(7373, 14747)
(7374, 7377)
(7374, 17213)
(7377, 14757)
(7379, 14759)
(7380, 7389)
(7380, 15023)
(7380, 15599)
(7390, 22171)
(7392, 7393)
(7392, 221

(11256, 11257)
(11270, 23077)
(11272, 11273)
(11274, 22551)
(11283, 22569)
(11286, 11287)
(11286, 11313)
(11298, 11299)
(11298, 11301)
(11310, 23187)
(11313, 22653)
(11318, 22637)
(11319, 22639)
(11319, 22641)
(11321, 22643)
(11322, 11331)
(11322, 23921)
(11325, 22801)
(11334, 11337)
(11337, 22677)
(11339, 22679)
(11340, 23519)
(11352, 11353)
(11352, 23759)
(11360, 22721)
(11375, 22751)
(11382, 11383)
(11384, 22769)
(11392, 11393)
(11393, 22787)
(11408, 24259)
(11418, 23897)
(11418, 23943)
(11422, 11423)
(11435, 22871)
(11446, 11447)
(11453, 22907)
(11454, 23453)
(11454, 23547)
(11460, 11463)
(11460, 23363)
(11463, 22929)
(11472, 24429)
(11481, 22963)
(11486, 22973)
(11496, 11497)
(11496, 11499)
(11501, 23003)
(11502, 11503)
(11504, 24463)
(11508, 23867)
(11513, 23027)
(11519, 23039)
(11535, 23071)
(11538, 24377)
(11540, 23081)
(11546, 23641)
(11548, 11549)
(11550, 24173)
(11568, 24599)
(11570, 23449)
(11578, 11579)
(11579, 23159)
(11586, 11589)
(11586, 23173)
(11592, 11593)
(11601, 23

In [29]:
n = 10
println(factors(n))
println(all_factors(n))
psu = sort(map(prod,unique(collect(powerset(all_factors(n)))))[2:end])'
println(psu)
println(factors(R(n)))
println([A(p) for p in collect(keys(factor(R(n))))]')
println()
@>> D_k filter(p->p[1] in psu) map(p->(p[2],p[1])) filter(p->isprime(p[1])) sort @print_seq

2 ⋅ 5
[2 5]
[2 5 10]
11 ⋅ 41 ⋅ 271 ⋅ 9091
[2 5 5 10]

(11, 2)
(41, 5)
(271, 5)
(9091, 10)


In [30]:
n = 100
println(factors(n))
println(all_factors(n))
psu = sort(map(prod,unique(collect(powerset(all_factors(n)))))[2:end])'
println(psu)
println(factors(R(n)))
println([A(p) for p in collect(keys(factor(R(n))))]')
println()
@>> D_k filter(p->p[1] in psu) map(p->(p[2],p[1])) filter(p->isprime(p[1])) sort @print_seq

2^2 ⋅ 5^2
[2 2 5 5]
[2 4 5 10 20 25 50 100]
11 ⋅ 41 ⋅ 101 ⋅ 251 ⋅ 271 ⋅ 3541 ⋅ 5051 ⋅ 9091 ⋅ 21401 ⋅ 25601 ⋅ 27961 ⋅ 60101 ⋅ 7019801 ⋅ 182521213001 ⋅ 14103673319201 ⋅ 78875943472201 ⋅ 1680588011350901
[2 5 4 50 5 20 50 10 25 25 20 100 100 25 100 50 100]

(11, 2)
(41, 5)
(101, 4)
(251, 50)
(271, 5)
(3541, 20)
(5051, 50)
(9091, 10)
(21401, 25)


In [31]:
n = 10^3
println(factors(n))
println(all_factors(n))
psu = sort(map(prod,unique(collect(powerset(all_factors(n)))))[2:end])'
println(psu)
#println(factors(R(n)))
#println([A(p) for p in collect(keys(factor(R(n))))]')
println()
@>> D_k filter(p->p[1] in psu) map(p->(p[2],p[1])) filter(p->isprime(p[1])) sort
#@>> D_k filter(p->p[1] in psu) map(p->(p[2],p[1])) filter(p->isprime(p[1])) sort map(first) sum

2^3 ⋅ 5^3
[2 2 2 5 5 5]
[2 4 5 8 10 20 25 40 50 100 125 200 250 500 1000]



18-element Array{Tuple{Int64,Int64},1}:
 (11, 2)      
 (41, 5)      
 (73, 8)      
 (101, 4)     
 (137, 8)     
 (251, 50)    
 (271, 5)     
 (401, 200)   
 (751, 125)   
 (1201, 200)  
 (1601, 200)  
 (3541, 20)   
 (4001, 500)  
 (5051, 50)   
 (9091, 10)   
 (21001, 250) 
 (21401, 25)  
 (24001, 1000)

Calculating D_k beforehand is very inefficient. Better to find another way.